#undef PLF_CONSTRUCT_ELEMENT
#undef PLF_DEFAULT_SUPPORT
#undef PLF_ALIGNMENT_SUPPORT
#undef PLF_INITIALIZER_LIST_SUPPORT
#undef PLF_TYPE_TRAITS_SUPPORT
#undef PLF_IS_ALWAYS_EQUAL_SUPPORT
#undef PLF_ALLOCATOR_TRAITS_SUPPORT
#undef PLF_VARIADICS_SUPPORT
#undef PLF_MOVE_SEMANTICS_SUPPORT
#undef PLF_NOEXCEPT
#undef PLF_NOEXCEPT_ALLOCATOR
#undef PLF_NOEXCEPT_SWAP
#undef PLF_NOEXCEPT_MOVE_ASSIGN
#undef PLF_CONSTEXPR
#undef PLF_CONSTFUNC
#undef PLF_CPP20_SUPPORT
#undef PLF_EXCEPTIONS_SUPPORT
#undef PLF_CPP11_SUPPORT
#undef PLF_CONSTEVAL_SUPPORT
#undef PLF_VOIDT_SUPPORT


#undef PLF_CONSTRUCT
#undef PLF_DESTROY
#undef PLF_ALLOCATE
#undef PLF_DEALLOCATE

#if defined(_MSVC_LANG) && (_MSVC_LANG >= 202002L) && _MSC_VER < 1951
	#pragma warning ( pop )
#endif

#undef PLF_COMPILER_DEFINES
